# Generated by Django 4.1.6 on 2023-03-22 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BlogPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.TextField(max_length=250, unique=True)),
                ("subtitle", models.TextField(max_length=250)),
                ("date", models.DateField(auto_now_add=True)),
                ("body", models.TextField()),
                ("img_url", models.TextField(max_length=250)),
            ],
            options={"verbose_name_plural": "blog_posts", "db_table": "blog_post",},
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("body", models.TextField()),
                ("date", models.DateField(auto_now_add=True)),
            ],
            options={"verbose_name_plural": "comments", "db_table": "comment",},
        ),
    ]
