# Generated by Django 4.1.6 on 2023-03-23 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dives", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="blogpost", name="img_url",),
        migrations.AddField(
            model_name="blogpost",
            name="pic",
            field=models.ImageField(blank=True, default="default.jpg", upload_to=""),
        ),
    ]
