# Generated by Django 4.1.6 on 2023-03-25 11:04

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dives", "0003_blogpost_author"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogpost",
            name="body",
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
        migrations.AlterField(
            model_name="blogpost",
            name="subtitle",
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name="blogpost",
            name="title",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
