# Generated by Django 4.1.6 on 2023-03-26 06:33

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("dives", "0004_alter_blogpost_body_alter_blogpost_subtitle_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="comment",
            options={"ordering": ["date"], "verbose_name_plural": "comments"},
        ),
        migrations.AddField(
            model_name="comment",
            name="author",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="comment",
            name="post",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="dives.blogpost",
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="body",
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
