# Generated by Django 4.1.6 on 2023-03-27 09:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("dives", "0005_alter_comment_options_comment_author_comment_post_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="LogBook",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dive_number", models.PositiveIntegerField()),
                ("date", models.DateField()),
                ("time", models.TimeField()),
                (
                    "country",
                    django_countries.fields.CountryField(blank=True, max_length=2),
                ),
                ("dive_site", models.CharField(max_length=30)),
                ("guide", models.CharField(max_length=30)),
                ("dive_body", models.CharField(max_length=30)),
                (
                    "dive_center",
                    models.CharField(
                        default="https://www.padi.com/dive-shops/nearby/?lang=en",
                        max_length=20,
                    ),
                ),
                ("duration", models.DurationField()),
                ("depth", models.FloatField()),
                ("nitrox", models.BooleanField(null=True)),
                ("air_left", models.IntegerField()),
                ("notes", models.TextField(max_length=200)),
                (
                    "pics",
                    models.FileField(blank=True, default="default.jpg", upload_to=""),
                ),
                ("log_date", models.DateField(auto_now_add=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"ordering": ["dive_number"],},
        ),
    ]
