# Generated by Django 4.1.6 on 2023-03-27 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dives", "0006_logbook"),
    ]

    operations = [
        migrations.RenameField(
            model_name="logbook", old_name="dive_body", new_name="buddy",
        ),
    ]
