# Generated by Django 4.1.6 on 2023-03-27 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dives", "0007_rename_dive_body_logbook_buddy"),
    ]

    operations = [
        migrations.AlterField(
            model_name="logbook",
            name="buddy",
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name="logbook",
            name="guide",
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name="logbook",
            name="notes",
            field=models.TextField(blank=True, max_length=200),
        ),
    ]
